on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate_citation:
    name: Validate CITATION.cff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LutrisEng/validate-cff@v1
