name: Check Citation.cff

on:
  push:
    paths:
      - 'CITATION.cff'
  pull_request:
    paths:
      - 'CITATION.cff'

jobs:
  validate_citation:
    name: Validate CITATION.cff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LutrisEng/validate-cff@v1.0.0
